# Generated by Django 6.0 on 2026-03-11 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'verbose_name': 'Mensaje de Contacto', 'verbose_name_plural': 'Mensajes de Contacto'},
        ),
    ]
