# Generated by Django 5.2.7 on 2026-05-11 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_alter_consulta_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('dni', models.CharField(max_length=20, verbose_name='DNI')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Respondido', 'Respondido'), ('Cerrado', 'Cerrado')], default='Pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_respondidos', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
            ],
            options={
                'verbose_name': 'Formulario de contacto',
                'verbose_name_plural': 'Formularios de contacto',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Respuesta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de respuesta')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='contacto.formulariocontacto', verbose_name='Formulario')),
            ],
            options={
                'verbose_name': 'Respuesta de contacto',
                'verbose_name_plural': 'Respuestas de contacto',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
    ]
