# Generated by Django 5.2.7 on 2026-05-11 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0004_mensajecliente_respuestamensaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Asignada', 'Asignada'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Completada', 'Completada')], default='Asignada', max_length=20)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aceptación')),
                ('fecha_completacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completación')),
                ('notas_asignacion', models.TextField(blank=True, verbose_name='Notas de asignación')),
                ('notas_veterinario', models.TextField(blank=True, verbose_name='Notas del veterinario')),
                ('asignado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='contacto.formulariocontacto', verbose_name='Formulario de contacto')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Veterinario')),
            ],
            options={
                'verbose_name': 'Asignación de solicitud',
                'verbose_name_plural': 'Asignaciones de solicitudes',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionVeterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('asignacion', 'Nueva asignación'), ('aceptacion', 'Solicitud aceptada'), ('rechazo', 'Solicitud rechazada'), ('mensaje', 'Nuevo mensaje')], max_length=20, verbose_name='Tipo de notificación')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='contacto.asignacionsolicitud', verbose_name='Asignación relacionada')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Veterinario')),
            ],
            options={
                'verbose_name': 'Notificación veterinario',
                'verbose_name_plural': 'Notificaciones veterinarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
