# Generated by Django 5.2.7 on 2026-05-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0005_asignacionsolicitud_notificacionveterinario'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariocontacto',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='formulariocontacto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
