# Generated by Django 5.2.7 on 2026-05-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0006_formulariocontacto_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariocontacto',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha preferida'),
        ),
        migrations.AddField(
            model_name='formulariocontacto',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora preferida'),
        ),
    ]
