# Generated by Django 6.0 on 2026-03-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_perfil_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='es_veterinario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
