# Generated by Django 5.2.7 on 2026-04-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_perfil_es_veterinario_perfil_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente / Dueño de mascota'), ('veterinario', 'Veterinario'), ('auxiliar', 'Auxiliar Veterinario'), ('recepcionista', 'Recepcionista'), ('admin', 'Administrador / Director')], default='cliente', max_length=20),
        ),
    ]
