# Generated by Django 6.0 on 2026-03-11 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_analisis_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analisis',
            options={'verbose_name': 'Análisis', 'verbose_name_plural': 'Análisis'},
        ),
    ]
