# Generated by Django 5.2.7 on 2026-05-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0007_auto_20260422_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='hora',
            field=models.TimeField(default='09:00'),
        ),
    ]
