# Generated by Django 5.2.7 on 2026-05-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('consulta', 'Consulta'), ('analisis', 'Análisis'), ('cirugia', 'Cirugía'), ('urgencia', 'Urgencia'), ('formulario_contacto', 'Formulario de Contacto'), ('mensaje_contacto', 'Mensaje de Duda')], max_length=20),
        ),
    ]
