# Generated by Django 6.0 on 2026-03-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=100)),
                ('tipo_cirugia', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Programada', 'Programada'), ('En Curso', 'En Curso'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Programada', max_length=20)),
                ('quirofano', models.CharField(max_length=50)),
            ],
        ),
    ]
