# Generated by Django 6.0 on 2026-03-11 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cirugias', '0002_alter_cirugia_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cirugia',
            options={'verbose_name': 'Cirugía', 'verbose_name_plural': 'Cirugías'},
        ),
    ]
