# Generated by Django 5.2.7 on 2026-04-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugias', '0004_cirugia_fecha_creacion_cirugia_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugia',
            name='tipo_animal',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Ave', 'Ave'), ('Roedor', 'Roedor'), ('Reptil', 'Reptil'), ('Otro', 'Otro')], default='Perro', max_length=20),
        ),
    ]
