# Generated by Django 5.2.7 on 2026-04-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugias', '0005_cirugia_tipo_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugia',
            name='tipo_animal_otro',
            field=models.CharField(blank=True, max_length=50, verbose_name='Especificar otro animal'),
        ),
    ]
