# Generated by Django 5.2.7 on 2026-05-18 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugias', '0008_cirugia_correo_cirugia_dni_cirugia_telefono'),
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugia',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cirugias', to='mascotas.mascota'),
        ),
    ]
