# Generated by Django 5.2.7 on 2026-05-18 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Ave', 'Ave'), ('Exótico', 'Exótico'), ('Otro', 'Otro')], default='Perro', max_length=50)),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kg', max_digits=5, null=True)),
                ('microchip', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('notas_medicas', models.TextField(blank=True, help_text='Alergias, condiciones crónicas, etc.', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL, verbose_name='Dueño')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
            },
        ),
    ]
