# Generated by Django 6.0 on 2026-03-23 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0002_remove_urgencia_atendido_urgencia_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='urgencia',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='urgencias', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
