# Generated by Django 5.2.7 on 2026-05-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0006_auto_20260422_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgencia',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='urgencia',
            name='dni',
            field=models.CharField(blank=True, max_length=20, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='urgencia',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono'),
        ),
    ]
