# Generated by Django 5.2.7 on 2026-05-18 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
        ('urgencias', '0007_urgencia_correo_urgencia_dni_urgencia_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgencia',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urgencias', to='mascotas.mascota'),
        ),
    ]
