# Generated by Django 5.2.7 on 2026-05-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0008_urgencia_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgencia',
            name='solicita_prioridad',
            field=models.BooleanField(default=False, verbose_name='¿Considera que requiere atención prioritaria inmediata?'),
        ),
        migrations.AlterField(
            model_name='urgencia',
            name='prioridad',
            field=models.CharField(choices=[('Pendiente', 'Pendiente de Valoración'), ('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Crítica', 'Crítica')], default='Pendiente', max_length=20),
        ),
    ]
