# Generated by Django 5.2.7 on 2026-04-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0006_consulta_tipo_animal_otro'),
    ]

    operations = [
    ]
