# Generated by Django 5.2.7 on 2026-05-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0007_auto_20260422_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('En Proceso', 'En Proceso'), ('Completado', 'Completado'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20),
        ),
    ]
