# Generated by Django 6.0 on 2026-03-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioEstetica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=100)),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True)),
                ('realizado', models.BooleanField(default=False)),
            ],
        ),
    ]
