# Generated by Django 5.2.7 on 2026-03-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estetica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicioestetica',
            name='realizado',
        ),
        migrations.AddField(
            model_name='servicioestetica',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Completado', 'Completado')], default='Pendiente', max_length=20),
        ),
    ]
