# Generated by Django 6.0 on 2026-03-11 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estetica', '0002_remove_servicioestetica_realizado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicioestetica',
            options={'verbose_name': 'Servicio de Estética', 'verbose_name_plural': 'Servicios de Estética'},
        ),
    ]
