"""
Django settings for vetct_web project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

"""
Django settings for vetct_web project.
VetCT es el nombre de la empresa, vetct_web es el proyecto Django.
"""

import os
from pathlib import Path
from decouple import config  # pip install python-decouple

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='clave-secreta-desarrollo-vetct-2024')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.vetct.com']

# Application definition - VETCT APPS
INSTALLED_APPS = [
    # Django core apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap4',
    
    # VetCT Apps - NUESTRAS APLICACIONES
    'inicio',           # Página principal
    'servicios',        # Servicios generales
    'urgencias',        # Servicio de urgencias
    'consultas',        # Consulta general
    'laboratorio',      # Análisis y laboratorio
    'estetica',         # Estética y peluquería
    'cirugias',         # Cirugías
    'vacunacion',       # Vacunación
    'tienda',           # Tienda online
    'contacto',         # Formularios de contacto
    'users',
]


# VetCT Configuration
VETCT_INFO = {
    'NOMBRE_EMPRESA': 'VetCT',
    'NOMBRE_COMPLETO': 'VetCT - Centro Veterinario Integral',
    'TELEFONO_PRINCIPAL': '+34 912 345 678',
    'TELEFONO_URGENCIAS': '+34 600 123 456',
    'EMAIL_CONTACTO': 'info@vetct.com',
    'DIRECCION': 'Av. Veterinaria 123, Ciudad Animal',
    'HORARIO_NORMAL': 'Lunes a Viernes: 9:00-20:00',
    'HORARIO_FIN_SEMANA': 'Sábados: 10:00-14:00',
    'REDES_SOCIALES': {
        'facebook': 'https://facebook.com/vetct',
        'instagram': 'https://instagram.com/vetct_veterinaria',
        'twitter': 'https://twitter.com/vetct',
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vetct_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates', 
            BASE_DIR / 'inicio/templates',
            BASE_DIR / 'tienda/templates',
            BASE_DIR / 'contacto/templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Context processor personalizado para VetCT
                'vetct_web.context_processors.vetct_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'vetct_web.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'Europe/Madrid'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (Uploaded by users)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Crispy Forms
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  
EMAIL_HOST = 'infoVetct@gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'inicio'